### ISSUE TITLE
Check and replace Gotify with ntfy.sh

### ISSUE THREAD

**Issue by JulianKropp** [ITLab-CC/Docker-Collection#29]
If [ntfy](https://ntfy.sh/) is better then gotify. Replace gotify with [ntfy](https://ntfy.sh/)

**Comment by criation** [comment]
Plz tell criteria that need to be checked

**Comment by JulianKropp** [comment]
It seems that notify is similar to gotify but supports iOS devices and gotify doesn't.

So if you want to create a docker file with traefik labels do it.

For the structure read the README.md.

You can create a .env.templ to specify what secrets are needed for your docker-compose.yml.

If any files or default configs are needed you can also create a folder named data.tmpl. 

For more information have a look into the README.md.

**Comment by criation** [comment]
So no quality checks are required?

**Comment by JulianKropp** [comment]
Design it the way, that it will work out of the box if possible.

Use the docker.sh script to generate an example.

./docker.sh -c ntfy

**Comment by JulianKropp** [comment]
Now there is a new Project. Called iGotify. Gotify for IOS. But I don't like how it's designed at the moment:

https://github.com/androidseb25/iGotify-Notification-Assistent/issues/4
